{
 "title": "OpenLDAP Exporter",
 "tags": [
  "OpenLDAP",
  "LDAP",
  "prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(openldap_dial, job)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(openldap_dial, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Max File Descriptors",
   "type": "stat",
   "description": "dn=\"cn=Max File Descriptors,cn=Connections,cn=Monitor\"",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Max File Descriptors,cn=Connections,cn=Monitor\",instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Referrals",
   "type": "stat",
   "description": "Referrals\tNumber of referrals",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "openldap_monitor_counter_object{dn=\"cn=Referrals,cn=Statistics,cn=Monitor\",instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dail",
   "type": "timeseries",
   "description": "Openldap dail",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "openldap_dial{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time since last slapd restart",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(openldap_monitored_object{dn=\"cn=Uptime,cn=Time,cn=Monitor\",instance=~\"$instance\", job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection rate",
     "type": "timeseries",
     "description": "Current rate of connections",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(openldap_monitor_counter_object{dn=\"cn=Current,cn=Connections,cn=Monitor\", instance=~\"$instance\", job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Connection number",
     "type": "timeseries",
     "description": "Current number of connections",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(openldap_monitor_counter_object{dn=\"cn=Current,cn=Connections,cn=Monitor\", instance=~\"$instance\", job=~\"$job\"})",
       "legendFormat": "Current"
      }
     ]
    }
   ]
  },
  {
   "title": "Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bytes",
     "type": "timeseries",
     "description": "cn=(.*?),cn=Statistics,cn=Monitor rate",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(openldap_monitor_counter_object{dn=~\"cn=Bytes,cn=Statistics,cn=Monitor\",instance=~\"$instance\", job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{dn}}"
      }
     ]
    },
    {
     "title": "Entries",
     "type": "timeseries",
     "description": "Entries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(openldap_monitor_counter_object{dn=~\"cn=Entries,cn=Statistics,cn=Monitor\",instance=~\"$instance\", job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{dn}}"
      }
     ]
    },
    {
     "title": "PDU",
     "type": "timeseries",
     "description": "PDU",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(openldap_monitor_counter_object{dn=~\"cn=PDU,cn=Statistics,cn=Monitor\",instance=~\"$instance\", job=~\"$job\"}[$__rate_interval])",
       "legendFormat": "{{dn}}"
      }
     ]
    },
    {
     "title": "cn=(.*?),cn=Statistics,cn=Monitor",
     "type": "timeseries",
     "description": "cn=(.*?),cn=Statistics,cn=Monitor",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "openldap_monitor_counter_object{dn=~\"cn=(.*?),cn=Statistics,cn=Monitor\",instance=~\"$instance\", job=~\"$job\"}",
       "legendFormat": "{{dn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations ",
     "type": "timeseries",
     "description": "Core operations",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openldap_monitor_operation{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{dn}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Waiters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read",
     "type": "timeseries",
     "description": "Read",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(openldap_monitor_counter_object{dn=\"cn=Read,cn=Waiters,cn=Monitor\", instance=~\"$instance\", job=~\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Write",
     "type": "timeseries",
     "description": "Write",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(openldap_monitor_counter_object{dn=\"cn=Write,cn=Waiters,cn=Monitor\", instance=~\"$instance\", job=~\"$job\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations rate",
     "type": "timeseries",
     "description": "Core operations rate",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "openldap_monitored_object{dn!=\"cn=Uptime,cn=Time,cn=Monitor\",instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{dn}}"
      }
     ]
    }
   ]
  }
 ]
}